# Generated by Django 4.0.4 on 2022-09-22 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cidade',
            name='estado',
            field=models.CharField(choices=[('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('PR', 'Paraná'), ('SC', 'Santa Catarina')], max_length=2),
        ),
        migrations.CreateModel(
            name='Viagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_saida', models.CharField(max_length=50)),
                ('local_destino', models.CharField(max_length=50)),
                ('parada', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Motoristas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Digite seu nome completo', max_length=50, verbose_name='Informe o Nome')),
                ('telefone', models.CharField(max_length=20, verbose_name='Informe o Telefone')),
                ('nascimento', models.DateField(verbose_name='Informe a Data de Nacimento')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('rg', models.CharField(max_length=20, verbose_name='Informe o RG')),
                ('cpf', models.CharField(max_length=20, verbose_name='Informe o CPF')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Digite seu nome completo', max_length=50, verbose_name='Informe o Nome')),
                ('telefone', models.CharField(max_length=20, verbose_name='Informe o Telefone')),
                ('nascimento', models.DateField(verbose_name='Informe a Data de Nacimento')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('rg', models.CharField(max_length=20, verbose_name='Informe o RG')),
                ('cpf', models.CharField(max_length=20, verbose_name='Informe o CPF')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
